# Generated by Django 3.2.4 on 2021-06-17 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='distributor',
        ),
        migrations.AddField(
            model_name='members',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
