# Generated by Django 3.2.4 on 2021-06-17 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='moneyDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('contactno', models.PositiveBigIntegerField()),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='foodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('contactno', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('food_type', models.CharField(choices=[('RAW', 'Rawfood'), ('COOKED', 'Cookedfood')], max_length=10)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
