# Generated by Django 3.2.4 on 2021-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210617_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sender_email', models.EmailField(max_length=30)),
                ('body', models.CharField(max_length=300)),
            ],
        ),
    ]
